### Register a user
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{"email": "test@gmail.com", 
"username": "test", 
"password": "1234", 
"firstName": "Test", 
"lastName": "Zhang", 
"birthDate": "2025-07-01", 
"phone": "1234567890", 
"role": "student", 
"school": "RM", 
"grade": 11}

### Login a user
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
"username": "ken", 
"password": "1234"
}